import tlj from '../src/assets/img/trending/TLJ.jpg';
import lk from '../src/assets/img/trending/LK.jpg';
import to from '../src/assets/img/trending/TO.jpg';
import par from '../src/assets/img/trending/PandR.jpg';
import thor from '../src/assets/img/trending/TR.jpg';
import d from '../src/assets/img/trending/D.jpg';

const movies = {
    tlj: {
        image: tlj,
        title: "Star Wars: Episode VIII: The Last Jedi",
        match: '98%',
        rating: 'PG-13',
        duration: '2h 31m',
        desc: "The last Jedi believes it's time for the Jedi to end. Hope may be lost, but one brave scavenger won't give up.",
        Starring: "Daisy Ridley, John Boyega, Mark Hamill",
        genre: 'Action, Adventure, Fantasy',

    },
    lukeCage: {
        image: lk,
        title: "Marvel's Luke Cage",
        match: '93%',
        rating: 'TV-MA',
        duration: '2 Seasons',
        desc: "When a sabotaged experiment gives him super strength and unbreakable skin, Luke Cage becomes a fugitive attempting to rebuild his life in Harlem and must soon confront his past and fight a battle for the heart of his city.",
        Starring: "Mike Colter, Simone Missick, Theo Rossi",
        genre: 'Action, Crime, Drama',
    },
    theOffice: {
        image: to,
        title: "The Office",
        match: '100%',
        rating: 'TV-14',
        duration: '9 Seasons',
        desc: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
        Starring: "Steve Carell, Jenna Fischer, John Krasinski",
        genre: 'Comedy',
    },
    PandR: {
        image: par,
        title: "Parks and Recreation",
        match: '100%',
        rating: 'TV-PG',
        duration: '7 Seasons',
        desc: "The absurd antics of an Indiana town's public officials as they pursue sundry projects to make their city a better place.",
        Starring: "Amy Poehler, Nick Offerman, Chris Pratt",
        genre: 'Comedy',
    },
    thor: {
        image: thor,
        title: "Thor: Ragnarok",
        match: '98%',
        rating: 'PG-13',
        duration: '2h 10m',
        desc: "When it rains, it pours for the God of Thunder. Stuck on a cosmic scrap heap, he's being hammered from all sides.",
        Starring: "Chris Hemsworth, Tom Hiddleston, Cate Blanchett",
        genre: 'Action, Adventure, Comedy',
    },
    dexter: {
        image: d,
        title: "Dexter",
        match: '99%',
        rating: 'TV-MA',
        duration: '8 Seasons',
        desc: "By day, mild-mannered Dexter is a blood-spatter analyst for the Miami police. But at night, he is a serial killer who only targets other murderers.",
        Starring: "Michael C. Hall, Jennifer Carpenter, David Zayas",
        genre: 'Crime, Drama, Mystery',
    },
    theOffice2: {
        image: to,
        title: "The Office",
        match: '100%',
        rating: 'TV-14',
        duration: '9 Seasons',
        desc: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
        Starring: "Steve Carell, Jenna Fischer, John Krasinski",
        genre: 'Comedy',
    },
    tlj2: {
        image: tlj,
        title: "Star Wars: Episode VIII: The Last Jedi",
        match: '98%',
        rating: 'PG-13',
        duration: '2h 31m',
        desc: "The last Jedi believes it's time for the Jedi to end. Hope may be lost, but one brave scavenger won't give up.",
        Starring: "Daisy Ridley, John Boyega, Mark Hamill",
        genre: 'Action, Adventure, Fantasy',

    },
    thor2: {
        image: thor,
        title: "Thor: Ragnarok",
        match: '98%',
        rating: 'PG-13',
        duration: '2h 10m',
        desc: "When it rains, it pours for the God of Thunder. Stuck on a cosmic scrap heap, he's being hammered from all sides.",
        Starring: "Chris Hemsworth, Tom Hiddleston, Cate Blanchett",
        genre: 'Action, Adventure, Comedy',
    },
    PandR2: {
        image: par,
        title: "Parks and Recreation",
        match: '100%',
        rating: 'TV-PG',
        duration: '7 Seasons',
        desc: "The absurd antics of an Indiana town's public officials as they pursue sundry projects to make their city a better place.",
        Starring: "Amy Poehler, Nick Offerman, Chris Pratt",
        genre: 'Comedy',
    },
    tlj3: {
        image: tlj,
        title: "Star Wars: Episode VIII: The Last Jedi",
        match: '98%',
        rating: 'PG-13',
        duration: '2h 31m',
        desc: "The last Jedi believes it's time for the Jedi to end. Hope may be lost, but one brave scavenger won't give up.",
        Starring: "Daisy Ridley, John Boyega, Mark Hamill",
        genre: 'Action, Adventure, Fantasy',

    },
    lukeCage2: {
        image: lk,
        title: "Marvel's Luke Cage",
        match: '93%',
        rating: 'TV-MA',
        duration: '2 Seasons',
        desc: "When a sabotaged experiment gives him super strength and unbreakable skin, Luke Cage becomes a fugitive attempting to rebuild his life in Harlem and must soon confront his past and fight a battle for the heart of his city.",
        Starring: "Mike Colter, Simone Missick, Theo Rossi",
        genre: 'Action, Crime, Drama',
    },
    PandR3: {
        image: par,
        title: "Parks and Recreation",
        match: '100%',
        rating: 'TV-PG',
        duration: '7 Seasons',
        desc: "The absurd antics of an Indiana town's public officials as they pursue sundry projects to make their city a better place.",
        Starring: "Amy Poehler, Nick Offerman, Chris Pratt",
        genre: 'Comedy',
    },
    theOffice3: {
        image: to,
        title: "The Office",
        match: '100%',
        rating: 'TV-14',
        duration: '9 Seasons',
        desc: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
        Starring: "Steve Carell, Jenna Fischer, John Krasinski",
        genre: 'Comedy',
    },
};

export default movies;